name: Deploy artifact

# Store an artifact in GitHub Packages on every merge to develop branch

on:
  push:
    branches:
      - develop
    tags:
      - latest

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        mkdir -p build
        cd build
        cmake ..
        make update -j
    - name: build
      run: |
        cd build
        make -j
        make install
    - name: check
      run: |
        cd build
        make check -j
    - name: package
      run: |
        cd build
        make package
        rm -rf out/_CPack_Packages
    - name: archive results
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: build/out


    - name: Publish to GitHub Packages
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
