name: CMake Build Matrix

on: [push, pull_request]

env:
  CMAKE_VERSION: "3.29.6"
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MinGW", artifact: "Windows-MinGW",
            os: windows-latest,
            cc: "gcc", cxx: "g++"
          }

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-cmake@v4
      with:
        cmake-version: ${{ env.CMAKE_VERSION }}
    - name: Configure Project
      run: |
        cmake \
          -S . \
          -B build \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -G "Ninja"  # or -G "Unix Makefiles" for compatibility
        
    - name: Build Project
      run: cmake --build build --config ${{ env.BUILD_TYPE }}


    - name: Run Tests (if any)
      run: ctest --output-on-failure
    
    - name: Install (optional)
      run: cmake --install build --prefix instdir

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.config.artifact }}-${{ github.run_id }}.tar.gz
        path: ${{ matrix.config.artifact }}-${{ github.run_id }}.tar.gz
